export default {
    idx: 0,
    leftDrawerOpen: true,
    alertVisible: false,
    process: [
        {
            title: '착수',
            normal: 2,
            err: 0,
            selected: true,
            img: 'icon1',
        },
        {
            title: '약품',
            normal: 10,
            err: 0,
            selected: false,
            img: 'icon2',
        },
        {
            title: '혼화/응집',
            normal: 10,
            err: 0,
            selected: false,
            img: 'icon3',
        },
        {
            title: '침전',
            normal: 8,
            err: 0,
            selected: false,
            img: 'icon4',
        },
        {
            title: '여과',
            normal: 6,
            err: 0,
            selected: false,
            img: 'icon5',
        },
        {
            title: 'GAC여과',
            normal: 3,
            err: 0,
            selected: false,
            img: 'icon6',
        },
        {
            title: '소독',
            normal: 2,
            err: 0,
            selected: false,
            img: 'icon7',
        },
        {
            title: '송수',
            normal: 20,
            err: 0,
            selected: false,
            img: 'icon8',
        },
    ],
    pumpMotor: [
        {
            name: '1',
            status: false,
            list: '송수모터/펌프 #1',
        },
        {
            name: '2',
            status: true,
            list: '송수모터/펌프 #2',
        },
        {
            name: '3',
            status: true,
            list: '송수모터/펌프 #3',
        },
        {
            name: '4',
            status: true,
            list: '송수모터/펌프 #4',
        },
        {
            name: '5',
            status: true,
            list: '송수모터/펌프 #5',
        },
        {
            name: '6',
            status: true,
            list: '송수모터/펌프 #6',
        },
        {
            name: '7',
            status: true,
            list: '송수모터/펌프 #7',
        },
        {
            name: '8',
            status: true,
            list: '송수모터/펌프 #8',
        },
        {
            name: '9',
            status: true,
            list: '송수모터/펌프 #9',
        },
        {
            name: '10',
            status: true,
            list: '송수모터/펌프 #10',
        },
    ],
    alertList: [
        {
            num: 1,
            time: '2021-06-15 15:00',
            list: '착수정 유입 조절 밸브 #1',
            info: '-',
            status: '전압이상',
        },
        {
            num: 2,
            time: '2021-06-15 15:00',
            list: '착수정 유입 조절 밸브 #2',
            info: '-',
            status: '전압이상',
        },
        {
            num: 3,
            time: '2021-06-15 15:00',
            list: '착수정 유입 조절 밸브 #3',
            info: '-',
            status: '전압이상',
        },
        {
            num: 4,
            time: '2021-06-15 15:00',
            list: '착수정 유입 조절 밸브 #4',
            info: '-',
            status: '전압이상',
        },
    ],
    pieNormalData: 0,
    pieErrData: 0,
    motors: [
        {
            id: 1,
            name: '송수펌프 #1',
            select: true,
        },
        {
            id: 2,
            name: '송수펌프 #2',
            select: false,
        },
        {
            id: 3,
            name: '송수펌프 #3',
            select: false,
        },
        {
            id: 4,
            name: '송수펌프 #4',
            select: false,
        },
        {
            id: 5,
            name: '송수펌프 #5',
            select: false,
        },
        {
            id: 6,
            name: '송수펌프 #6',
            select: false,
        },
    ],
};
