#구미
server:
  port: 10016

spring:
  datasource:
    #DB세팅
    url: jdbc:mariadb://localhost:3306/PMS_DB?serverTimezone=Asia/Seoul
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092, localhost:9092, localhost:9093
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest



##kafka setting
kafka:
  centerId: gumi
  #topic
  topic:
    scada1:
      name: FGMWGS1_data
    scada2:
      name: FGMWGS2_data
    scada3:
      name: FGMWGS_PMS_rawdata
  #group id
  group:
    scada1:
      id: FGMWGS1_PMS_rawdata_240311_1
    scada2:
      id: FGMWGS2_PMS_rawdata_240311_1
    scada3:
      id: FGMWGS3_PMS_rawdata_240118_7
  new:
    group:
      id: FGMWGS_PMS_rawdata_first_1

