# -*- coding: utf-8 -*-
"""main_v2.3.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UWk3tghc-yVcTOqWqlBKur4UEV3zWqFV
"""

import json
import pandas as pd
import os
import numpy as np
from datetime import datetime, timedelta
import pickle
from keras.models import load_model
import time
import pymysql
from pymysql.cursors import DictCursor
import schedule
from pytz import timezone
from sqlalchemy import create_engine

def initialization(sheetname, model_name, mode):
    worksheet = pd.read_excel('/home/app/pump2/GS_taglist.xlsx', sheet_name = sheetname)

    if mode == 'PRES':
        df = worksheet.loc[
            (worksheet['비고'] != 'NU') &
            (worksheet['사용'] == 'Y') &
            (worksheet['데이터>200만'] == 'Y') &
            (worksheet['변수명'].str[0] == 'P')
            ].reset_index(drop=True)

    elif mode == 'FLUX':
        df = worksheet.loc[
            (worksheet['비고'] != 'NU') &
            (worksheet['사용'] == 'Y') &
            (worksheet['데이터>200만'] == 'Y') &
            (worksheet['변수명'].str[0] != 'P')
            ].reset_index(drop=True)

    load_dir ="/home/app/pump2/"
    model = load_model(f"{load_dir}saved_model/{model_name}.keras", custom_objects={'custom_loss': custom_loss})

    loaded_scalers = {}
    for feature in df.변수명:
        save_path = os.path.join(load_dir, f"saved_scaler/{model_name}/{feature}_scaler.pkl")
        with open(save_path, "rb") as f:
            loaded_scalers[feature] = pickle.load(f)
    return df, model, loaded_scalers

def open_db():
    print("open_db")
    with open('/home/app/pump2/libs/connections.json') as f:
        # 커넥션 정보를 불러옴
        connection = json.load(f)['maria-ems-db-gs']
        print('connection', connection)
        connection = pymysql.connect(**connection)
        print('connected', connection)
    return connection

def get_db_config():
    db_config = {               ## DB 연결정보 #--#
        "host": "localhost",
        "port": 3306,
        "user": "ems_user",
        "password": "CHANGE_ME",
        "db": "EMS_DB"
    }
    return db_config

def pred_pump(df_result_q, df_result_p, mode):

    df_result = pd.merge(df_result_q, df_result_p, on='Datetime', how='outer')
    pump_grp = '0'
    if mode == 'OLD':
        pump_dfs = []
        print('####pred_pump')
        pump_grp = '1'
        columns_checked = {'Q_GS_OLD_Predict': 'Q_GS_OLD_Predict' in df_result_q.columns,
                           'P_GS_OLD_Predict': 'P_GS_OLD_Predict' in df_result_p.columns} # 예측값 존재여부 확인
        print(df_result_q)
        print(df_result_p)
        
        
        
        for timestamp, row in df_result.iterrows():
            print('row', row)
            # 조건 수정
            if all(columns_checked.values()):
                freqs, pump_yn = [None, None, None, None, None, None, None], [0, 1, 0, 0, 1, 0, 1] # else 조건 (default)
                Q = row['Q_GS_OLD_Predict']
                if Q >= 19000:
                    pump_yn = [0, 0, 0, 1, 1, 1, 1]
                elif 17500 <= Q < 19000:
                    pump_yn = [0, 1, 0, 1, 0, 1, 1]
                elif 16800 <= Q < 17500:
                    pump_yn = [0, 1, 0, 1, 1, 0, 1]
                elif 16000 <= Q < 16800:
                    pump_yn = [0, 0, 0, 1, 1, 1, 0]
                elif 14500 <= Q < 16000:
                    pump_yn = [0, 0, 0, 1, 1, 0, 1]
                    
                pump_df = create_pump_df(timestamp, row['Q_GS_OLD_Predict'], row['P_GS_OLD_Predict'], range(1, 8), pump_yn, freqs, 1) # range 입력 시 range(a, a+n) 형태로 사용 (n: 펌프 개수)
                pump_dfs.append(pump_df)

    elif mode == 'NEW':
        pump_dfs = []
        columns_checked = {'Q_GS_NEW_Predict': 'Q_GS_NEW_Predict' in df_result_q.columns,
                           'P_GS_NEW_Predict': 'P_GS_NEW_Predict' in df_result_p.columns} # 예측값 존재여부 확인
        pump_grp = '2'
        for timestamp, row in df_result.iterrows():
            print('row', row)
            # 조건 수정
            if all(columns_checked.values()):
                freqs, pump_yn = [None, None, None, None], [0, 0, 1, 0] # else 조건 (default)
                Q = row['Q_GS_NEW_Predict']

                pump_df = create_pump_df(timestamp, row['Q_GS_NEW_Predict'], row['P_GS_NEW_Predict'], range(1, 5), pump_yn, freqs, 2) # range 입력 시 range(a, a+n) 형태로 사용 (n: 펌프 개수)
                pump_dfs.append(pump_df)

   
    print('#############################')
    final_pump_df = pd.concat(pump_dfs).reset_index(drop=True)
    print('#############################')
    
    nowStr = datetime.now().strftime('%H%M')
    final_pump_df['OPT_IDX'] = final_pump_df['RGSTR_TIME'].dt.strftime('780-344-PRI-'+pump_grp+':%Y%m%d%H%M%S-'+nowStr)
    final_pump_df['PRDCT_TIME_DIFF'] = final_pump_df['RGSTR_TIME'].dt.strftime('%M').astype(int) - int(final_pump_df.iloc[0]['RGSTR_TIME'].strftime('%M')) + 1
    #del pump_dfs['timestamp']
    final_pump_df['RGSTR_TIME'] = final_pump_df['RGSTR_TIME'] + pd.Timedelta(hours=1)
    print(final_pump_df)

    db_config = get_db_config() # DB 연결정보
    database_connection_string = f"mysql+pymysql://{db_config['user']}:{db_config['password']}@{db_config['host']}:{db_config['port']}/{db_config['db']}"
    engine = create_engine(database_connection_string)
    final_pump_df.to_sql('TB_CTR_PUMPYN_RST', engine, if_exists='append', index=False)  # DB에 데이터 저장 #--#

    print('###INSERT TB_CTR_PUMPYN_RST')
    return pump_df

def get_db_df(connection, tag_name):
    print(tag_name)
    cursor  = connection.cursor(DictCursor)
    cursor.execute(
        f"""
            select TS Datetime, VALUE from EMS_DB.TB_RAWDATA tr where TAGNAME = '{tag_name}' order by ts desc limit 60
        """
    )
    data = cursor.fetchall()
    print(tag_name+"["+str(len(data))+"] end")
    return data

def set_index_df(df, window_size = 60):    # DataFrame의 인덱스를 재설정하고 Datetime 열을 날짜/시간 형식으로 변환
    df = df.reset_index(drop=True)
    df['Datetime'] = pd.to_datetime(df['Datetime'])
    df = df.iloc[-window_size:]  # 'Datetime' 열을 기준으로 지난 60분간의 데이터만 가져오기
    df = df.set_index('Datetime')
    return df

def custom_loss(y_true, y_pred):
    import tensorflow as tf
    from keras.losses import mean_squared_error
    # 패딩이 아닌 값을 식별하기 위한 마스크 생성.
    mask = tf.reduce_any(tf.not_equal(y_true, 10), axis=-1, keepdims=True)
    mask = tf.cast(mask, tf.float32)

    # 손실 계산에 사용할 y_true, y_pred에 마스크 적용
    y_true_masked = tf.multiply(y_true, mask)
    y_pred_masked = tf.multiply(y_pred, mask)

    # 마스크가 적용된 상태에서 MSE 손실 계산
    loss = mean_squared_error(y_true_masked, y_pred_masked)

    # 마스크가 적용된 요소의 평균으로 손실을 계산
    return tf.reduce_sum(loss) / tf.reduce_sum(mask)

def create_pump_df(timestamp, Q_pred, P_pred, pump_idxs, pump_yn, freqs, pump_grp):
    return pd.DataFrame({
        'RGSTR_TIME': [timestamp] * len(pump_idxs),
        'pump_idx': list(pump_idxs),
        'pump_yn': pump_yn,
        'FREQ': freqs,
        'PUMP_GRP': pump_grp,
        'TUBE_PRSR_PRDCT' : Q_pred,
        'PRDCT_MEAN' : P_pred
    })

def Predict_5min(name, model_name, mode = 'FLUX'):
    KST = timezone('Asia/Seoul')
    start = time.time()
    print(f"실행 시작: {str(datetime.now().astimezone(KST)).split('.')[0]} (KTC)")

    df, model, loaded_scalers = initialization(name, model_name, mode = mode)
    data_df = pd.DataFrame()

    db_connection = open_db()
    for i in range(len(df)):
        data_df[f"{df.변수명[i]}"] = set_index_df(pd.DataFrame(get_db_df(db_connection, f"{df.태그명[i]}")))
    print(f"imported data ...")
    db_connection.close()

    print(f"imported data ...")
    df_datetime = data_df.reset_index(drop=False)['Datetime']
    df_to_sequence = data_df.copy().reset_index(drop=True)    # 데이터셋 준비
    print("------------------------------------------------------------")

    for feature in df.변수명:
        df_to_sequence[feature] = loaded_scalers[feature].transform(df_to_sequence[[feature]]) # 데이터 스케일링

    testset = df_to_sequence.copy() # 실제 적용 시 주석 해제
    testset = testset.fillna(testset.mean())

    d_testX = np.expand_dims(np.array(testset[list(df.loc[df['비고'] != 'NU'].변수명)]), axis=0)

    testPredict = model.predict(d_testX)
    testPredict_result = testPredict[:,-step_topredict:,:]

    start_time_predict_str = str(df_datetime.values[-1]).split('.')[0]
    print(f"예측 시점 : {start_time_predict_str} (KTC)")
    start_time_predict = datetime.strptime(start_time_predict_str, '%Y-%m-%dT%H:%M:%S')

    datetime_list = []
    for i in range(step_topredict+1):
        current_time = start_time_predict + i * timedelta(minutes=1)
        datetime_list.append(current_time)
    df_result = pd.DataFrame(datetime_list[1:], columns = ['Datetime'])
    df_result = df_result.set_index('Datetime')

    for k in range(testPredict.shape[2]):
         df_result[f"{list(df.loc[df['비고'] == 'target'].변수명)[k]}_Predict"] = loaded_scalers[list(df.loc[df['비고'] == 'target'].변수명)[k]].inverse_transform(testPredict_result[:,:,k]).flatten()

    print(f"실행 시간 : {time.time() - start :.2f} 초")
    print(f"{step_topredict}분 후 예측 : ")
    df_result_str = df_result.copy()
    df_result_str.columns = [df.loc[df['비고'] == 'target']['태그 설명']]
    print(df_result_str)

    return df_result_str, df_result

def pred_and_load_gs():
    _, df_result_flux = Predict_5min('Gosan','gs_v10', mode = 'FLUX')
    _, df_result_pres = Predict_5min('Gosan','gs_v11', mode = 'PRES')

    final_pump_old = pred_pump(df_result_flux, df_result_pres, 'OLD') #구정수장 펌프예측
    final_pump_new = pred_pump(df_result_flux, df_result_pres, 'NEW') #신정수장 펌프예측
    return final_pump_old, final_pump_new

##### 한 번만 실행할 경우 주석해제 #####
#window_size = 60
#step_topredict = 5 # 예측할 시간 = 5분

#pred_and_load_gs()

### 스케줄 사용 시 주석 해제 후 시트명, 모델 버전 확인
window_size = 60
step_topredict = 5 # 예측할 시간 = 5분
for minute in range(0, 55, 5):
    schedule.every().hour.at(f":{minute:02}").do(pred_and_load_gs)

while True:
    schedule.run_pending()
    time.sleep(1)