### hp - \uD574\uD3C9 ###

#Server setting
server.port=10014

#DB Connections setting
#spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/EMS_DB?serverTimezone=Asia/Seoul
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


#kafka setting
kafka.topic.scada1.name=FHPIGS1_data
kafka.topic.scada2.name=FHPIGS2_data

kafka.group.scada1_1.id=FHPIGS1_ems_api_20250120_1_S1
kafka.group.scada1_2.id=FHPIGS2_ems_api_20250120_1_S1

kafka.group.scada2_1.id=FHPIGS1_ems_api_20250120_1_S2
kafka.group.scada2_2.id=FHPIGS2_ems_api_20250120_1_S2

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.bootstrap-servers-1=localhost:9092
spring.kafka.bootstrap-servers-2=localhost:9092


#kafka Setting 2(\uAD6C\uBBF8 kafka)
kafka.topic.scada3.name=FGMWGS1_data
kafka.topic.scada4.name=FGMWGS2_data
kafka.group.scada3.id=FHPIGS1_GM_ems_api_231222_1
kafka.group.scada4.id=FHPIGS2_GM_ems_api_231222_1
kafka.new.group2.id=FGMWGS1_ems_api_first_1
spring.kafka.bootstrap-servers2=localhost:9092, localhost:9092, localhost:9093

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.auto-offset-reset=latest
#logging.level.org.springframework.kafka=DEBUG