### gm - \uAD6C\uBBF8 ###

#Server setting
server.port=10014

#DB Connections setting
#spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/EMS_DB?serverTimezone=Asia/Seoul
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


#kafka setting
kafka.topic.scada1.name=FGMWGS1_data
kafka.topic.scada2.name=FGMWGS2_data

kafka.group.scada1_1.id=FGMWGS1_ems_api_20250120_2_S1
kafka.group.scada1_2.id=FGMWGS2_ems_api_20250120_2_S1

kafka.group.scada2_1.id=FGMWGS1_ems_api_20250120_2_S2
kafka.group.scada2_2.id=FGMWGS2_ems_api_20250120_2_S2

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.bootstrap-servers-1=localhost:9092
spring.kafka.bootstrap-servers-2=localhost:9092

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.auto-offset-reset=latest
#logging.level.org.springframework.kafka=DEBUG