### wm - \uC6B4\uBB38 ###

#Server setting
server.port=10014

#DB Connections setting
#spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/EMS_DB?serverTimezone=Asia/Seoul
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


#kafka setting
kafka.topic.scada1.name=FWMWGS1_data
kafka.topic.scada2.name=FWMWGS2_data

kafka.group.scada1_1.id=FWMWGS1_ems_api_20250120_2_S1
kafka.group.scada1_2.id=FWMWGS2_ems_api_20250120_2_S1

kafka.group.scada2_1.id=FWMWGS1_ems_api_20250120_2_S2
kafka.group.scada2_2.id=FWMWGS2_ems_api_20250120_2_S2


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.bootstrap-servers-1=localhost:9092
spring.kafka.bootstrap-servers-2=localhost:9092



spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.auto-offset-reset=latest
#logging.level.org.springframework.kafka=DEBUG


### \uC6B4\uC804\uD604\uD669 \uBCC0\uC218 - \uD604\uC7AC \uC6B4\uBB38 ver

### \uACC4\uD1B5 \uAD6C\uBD84\uC5C6\uB294 \uB370\uC774\uD130

# \uD38C\uD504 IDX \uBCC4 \uAC00\uB3D9 \uB300\uC218
dstrb.pump.level={\
    1:{\
        1:1,\
        2:1,\
        3:1,\
        4:1\
    }\
}
# \uD38C\uD504 \uBCC4 \uC608\uCE21 \uC804\uB825 \uACC4\uC0B0 \uAC12
dstrb.prdct.pwrCal.idx={\
    1:{\
        1:0.0021,\
        2:0.0019,\
        3:0.0022,\
        4:0.0021\
    }\
}

dstrb.prdct.pumpComb.target.min={\
    1:{\
    }\
}
dstrb.prdct.pumpComb.target.max.down={\
    1:{\
    }\
}
dstrb.prdct.pumpComb.target.max.up={\
    1:{\
    }\
}
dstrb.prdct.pumpComb.target.level={\
    1:{\
        "H1_Predict" : 365\
    }\
}
#  \uC218\uB450\uADF8\uB8F9 \uC800\uD56D \uC720\uB7C9 : \uC804\uCCB4 \uC720\uB7C9\uC5D0\uC11C \uC81C\uC678\uD560 \uC720\uB7C9\uC758 dstrb_id
dstrb.headLoss.flow={\
    1:{"A":[]}\
}
# PUMP_YN \uD14C\uC774\uBE14\uC5D0 \uB4E4\uC5B4\uAC08 OPT_IDX \uD0DC\uADF8 \uAC12
dstrb.optidx=865-337-FRI-

# \uC6B4\uC804\uD604\uD669 \uD398\uC774\uC9C0\uC5D0 \uBCF4\uC5EC\uC904 \uC720\uB7C9 \uD0DC\uADF8 \uBC0F dstrb_id(\uC608\uCE21 \uBCC0\uC218 id)
dstrb.prdct.dstrbId={\
            "flowTag":[\
                "565-340-FRI-4000",\
                "565-340-FRI-8002",\
                "565-340-FRI-8116",\
                "565-340-FRI-8111",\
                "565-340-FRI-8113"\
            ],\
            dstrb_q_id:[\
                "Q_WM_PREDICT",\
                "Q3_PREDICT",\
                "Q4_2_PREDICT",\
                "Q6_PREDICT",\
                "Q8_PREDICT"\
            ],\
            dstrb_p_id:[\
                "P_WM_PREDICT",\
                "P3_PREDICT"\
            ],\
            level_tag:[\
                "565-340-SWI-8101",\
                "565-340-LEI-8115",\
                "565-340-LEI-8113",\
                "565-340-LEI-8111"\
            ]\
  }

# excel \uB2E4\uC6B4\uB85C\uB4DC\uC5D0\uC11C \uC81C\uC678\uD560 \uBD84\uAE30\uC758 epa dstrb_id
dstrb.excel.notSrttn={\
            "epaFlow":[],\
            "epaPressure":[]\
  }

# \uC218\uB450 \uC190\uC2E4\uAC12 \uACC4\uC0B0 \uACE0\uC815 \uC0C1\uC218
dstrb.headLoss.cal={\
        1:{\
            "A":9.54\
        }\
}
### \uACC4\uD1B5 \uAD6C\uBD84(\uD14C\uC2A4\uD2B8 DB \uAE30\uC900 1:\uAD6C\uC815\uC218\uC9C0, 2: \uC2E0\uC815\uC218\uC9C0)

# \uC218\uB450 \uADF8\uB8F9\uBCC4 id \uB9AC\uC2A4\uD2B8
dstrb.headLoss.grp={\
    1:{\
        "A":["A"]\
    }\
}

# \uACC4\uD1B5\uBCC4 \uC608\uCE21 dstrb_id
dstrb.prdct.pumpDstrbId={\
        1:{\
            "flow":"Q_WM_Predict",\
            "pressure":"P_WM_Predict"\
        }\
    }

# \uACC4\uD1B5\uBCC4 \uC6B4\uC804\uD604\uD669 \uC608\uCE21 \uC804\uB825 \uACE0\uC815 \uC0C1\uC218
dstrb.prdct.pwrCal.calVal={\
        1:{\
            "prdctPwrFlow":-0.00009077,\
            "prdctPwrPress":0.000004923,\
            "prdctPwrDefault":0.0652\
        }\
    }