spring.profiles.active=dev
#spring.profiles.active=ba
#spring.profiles.active=gs
#spring.profiles.active=gr
#spring.profiles.active=gm
#spring.profiles.active=gm2
#spring.profiles.active=gu
#spring.profiles.active=ss
#spring.profiles.active=hy
#spring.profiles.active=hp
#spring.profiles.active=ji
#spring.profiles.active=wm

#Swagger setting
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

#Mybatis setting
mybatis.mapper-locations=classpath:sqlmapper/mysql/**/*.xml
mybatis.config-location=classpath:sqlmapper/config/config.xml

#log setting
log.config.path=/workspace/container_volumes/logs/ems_api
log.config.filename=application.log
error.log.config.filename=error.log


logging.level.org.apache.kafka=ERROR
logging.level.kafka=ERROR
logging.level.org.springframework.kafka=ERROR

#Tag setting
tag.value.mw.unit=1000
tag.value.mwh.unit=1000
tag.value.uk.unit=0.0000001
tag.value.uKh.unit=0.0000001
tag.value.default.rate.idx=1
tag.value.default.rate.fee=8000
tag.value.default.frq=100
tag.value.default.elec=1000
tag.value.co2=0.424

time.diff.min=2

#EXCEL Setting
#?????
excel.sheet.title.power.all=\uC804\uB825\uC0AC\uC6A9\uB7C9
#??????
excel.sheet.title.power.zone=\uC2DC\uC124\uBCC4\uC0AC\uC6A9\uB7C9
#??????????(kWh)
excel.sheet.title.power.time=\uC2DC\uAC04\uB300\uBCC4\uC804\uB825\uC0AC\uC6A9\uD604\uD669(kWh)
#??????
excel.sheet.title.pump=\uD38C\uD504\uAC00\uB3D9\uC774\uB825
#???????(m)
excel.sheet.title.tank=\uC8FC\uC694\uBC30\uC218\uC9C0\uC218\uC704(m)



