### dev - \uAC1C\uBC1C ###

#Server setting
server.port=9000
# server.port=30201

#DB Connections setting
#spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/ems_db

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


### \uC6B4\uC804\uD604\uD669 \uBCC0\uC218 - \uD604\uC7AC \uACE0\uC0B0\uB9CC \uC788\uC74C ###

### \uACC4\uD1B5 \uAD6C\uBD84\uC5C6\uB294 \uB370\uC774\uD130

# \uD38C\uD504 IDX \uBCC4 \uAC00\uB3D9 \uB300\uC218
dstrb.pump.level={\
      0:{\
        1:0.5,\
        2:0.5,\
        3:0.5,\
        4:1,\
        5:1,\
        6:1,\
        7:1,\
        8:1,\
        9:1,\
        10:1,\
        11:0.5\
    },\
    1:{\
        1:0.5,\
        2:0.5,\
        3:0.5,\
        4:1,\
        5:1,\
        6:1,\
        7:1\
    },\
    2:{\
        8:1,\
        9:1,\
        10:1,\
        11:0.5\
    }\
}
# \uD38C\uD504 \uBCC4 \uC608\uCE21 \uC804\uB825 \uACC4\uC0B0 \uAC12
dstrb.prdct.pwrCal.idx={\
    1:{\
        1:-31.0516,\
        2:10.4872,\
        3:10.3676,\
        4:15.9066,\
        5:13.5402,\
        6: 16.9349,\
        7: 11.7216\
    },\
    2:{\
        8:12.2984,\
        9:12.1002,\
        10:10.6296,\
        11:8.2559\
    }\
}

dstrb.prdct.pumpComb.target.min={\
    1:{\
        "P3_Predict" : 10.4,\
        "P5_Predict" : 10.8,\
        "P48_Predict" : 10,\
        "P54_Predict" : 8.6,\
        "P6_Predict" : 11.9\
    },\
    2:{\
        "P3_Predict" : 10.4,\
        "P5_Predict" : 10.8,\
        "P48_Predict" : 10,\
        "P54_Predict" : 8.6,\
        "P6_Predict" : 11.9\
    }\
}
dstrb.prdct.pumpComb.target.max.down={\
    1:{\
        "P3_Predict" : 8.3,\
        "P5_Predict" : 9.05,\
        "P48_Predict" : 8.3,\
        "P54_Predict" : 8.05,\
        "P6_Predict" : 9.9\
    },\
    2:{\
        "P3_Predict" : 8.3,\
        "P5_Predict" : 9.05,\
        "P48_Predict" : 8.3,\
        "P54_Predict" : 8.05,\
        "P6_Predict" : 9.9\
    }\
}
dstrb.prdct.pumpComb.target.max.up={\
    1:{\
        "P3_Predict" : 7.9,\
        "P5_Predict" : 8.6,\
        "P48_Predict" : 8,\
        "P54_Predict" : 7.76,\
        "P6_Predict" : 9.32\
    },\
    2:{\
        "P3_Predict" : 7.9,\
        "P5_Predict" : 8.6,\
        "P48_Predict" : 8,\
        "P54_Predict" : 7.76,\
        "P6_Predict" : 9.32\
    }\
}
dstrb.prdct.pumpComb.target.level={\
    1:{\
        "701-367-LEI-8001": 5.5,\
        "701-367-LEI-8005": 5.3\
    },\
    2:{\
        "701-367-LEI-8001": 5.5,\
        "701-367-LEI-8005": 5.3\
    }\
}
#  \uC218\uB450\uADF8\uB8F9 \uC800\uD56D \uC720\uB7C9 : \uC804\uCCB4 \uC720\uB7C9\uC5D0\uC11C \uC81C\uC678\uD560 \uC720\uB7C9\uC758 dstrb_id
dstrb.headLoss.flow={\
  0:{\
        "A4":[]\
  }\
}
# PUMP_YN \uD14C\uC774\uBE14\uC5D0 \uB4E4\uC5B4\uAC08 OPT_IDX \uD0DC\uADF8 \uAC12
dstrb.optidx=865-337-FRI-

# \uC6B4\uC804\uD604\uD669 \uD398\uC774\uC9C0\uC5D0 \uBCF4\uC5EC\uC904 \uC720\uB7C9 \uD0DC\uADF8 \uBC0F dstrb_id(\uC608\uCE21 \uBCC0\uC218 id)
dstrb.prdct.dstrbId={\
            "flowTag":[\
                "701-367-FRI-4004",\
                "701-367-FRI-4001",\
                "701-367-FRI-8661",\
                "701-367-FRI-8003",\
                "701-367-FRI-8008",\
                "701-367-FRI-8005",\
                "701-367-FRI-8007"\
            ],\
            dstrb_q_id:[\
                "Q_GS_NEW_PREDICT",\
                "Q_GS_OLD_PREDICT",\
                "Q1_PREDICT",\
                "Q3_PREDICT",\
                "Q5_PREDICT",\
                "Q6_PREDICT",\
                "Q48_PREDICT",\
                "Q54_PREDICT"\
                ],\
            dstrb_p_id:[\
                "P_GS_NEW_PREDICT",\
                "P_GS_OLD_PREDICT",\
                "P1_PREDICT",\
                "P3_PREDICT",\
                "P5_PREDICT",\
                "P6_PREDICT",\
                "P48_PREDICT",\
                "P54_PREDICT"\
            ],\
            level_tag:[\
                "701-367-LEI-4001",\
                "701-367-LEI-4011",\
                "701-367-LEI-4008",\
                "701-367-LEI-8001",\
                "701-367-LEI-8005",\
                "701-367-LEI-8006",\
                "701-367-LEI-8009"\
            ],\
            pressureTag:[\
                "701-367-PRI-4019",\
                "701-367-PRI-4010",\
                "701-367-PRI-8657",\
                "701-367-PRI-8661",\
                "701-367-PRI-8002",\
                "701-367-PRI-8006",\
                "701-367-PRI-8004",\
                "701-367-PRI-8005"\
            ]\
  }

# excel \uB2E4\uC6B4\uB85C\uB4DC\uC5D0\uC11C \uC81C\uC678\uD560 \uBD84\uAE30\uC758 epa dstrb_id
dstrb.excel.notSrttn={\
            "epaFlow":[],\
            "epaPressure":[]\
  }

# \uC218\uB450 \uC190\uC2E4\uAC12 \uACC4\uC0B0 \uACE0\uC815 \uC0C1\uC218
dstrb.headLoss.cal={\
      0:{\
        "A4":3.91\
      }\
}
### \uACC4\uD1B5 \uAD6C\uBD84(\uD14C\uC2A4\uD2B8 DB \uAE30\uC900 1:\uAD6C\uC815\uC218\uC9C0, 2: \uC2E0\uC815\uC218\uC9C0)

# \uC218\uB450 \uADF8\uB8F9\uBCC4 id \uB9AC\uC2A4\uD2B8
dstrb.headLoss.grp={\
      0:{\
            "A4":["A","B","D","E","H","K"]\
      }\
}

# \uACC4\uD1B5\uBCC4 \uC608\uCE21 dstrb_id
dstrb.prdct.pumpDstrbId={\
        1:{\
            "flow":"Q_GS_OLD_Predict",\
            "pressure":"P_GS_OLD_Predict"\
        },\
        2:{\
            "flow":"Q_GS_NEW_Predict",\
            "pressure":"P_GS_NEW_Predict"\
        }\
    }

# \uACC4\uD1B5\uBCC4 \uC6B4\uC804\uD604\uD669 \uC608\uCE21 \uC804\uB825 \uACE0\uC815 \uC0C1\uC218
dstrb.prdct.pwrCal.calVal={\
        2:{\
            "prdctPwrFlow":0.0586,\
            "prdctPwrPress":-10.2836,\
            "prdctPwrDefault":67.9458\
        },\
        1:{\
            "prdctPwrFlow":0.0049,\
            "prdctPwrPress":-36.6407,\
            "prdctPwrDefault":264.7133\
        }\
    }